/**
 * @fileOverview A self-review AI agent to evaluate and improve AI responses.
 *
 * - selfReview - A function that reviews an AI's response to a user prompt.
 * - SelfReviewInput - The input type for the selfReview function.
 * - SelfReviewOutput - The return type for the selfReview function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

export const SelfReviewInputSchema = z.object({
  userPrompt: z.string().describe("The original prompt from the user."),
  aiResponse: z.string().describe("The initial response generated by the AI."),
});
export type SelfReviewInput = z.infer<typeof SelfReviewInputSchema>;

export const SelfReviewOutputSchema = z.object({
  summaryEvaluation: z.enum(['Good', 'Needs Improvement']).describe("A brief evaluation of the response."),
  issuesFound: z.string().optional().describe("Any specific issues found in the response."),
  suggestedFixes: z.string().optional().describe("Suggestions for how to improve the response."),
  finalVerdict: z.enum(['Use as-is', 'Revise']).describe("The final recommendation on whether to use the response."),
});
export type SelfReviewOutput = z.infer<typeof SelfReviewOutputSchema>;

const selfReviewPrompt = ai.definePrompt({
  name: 'selfReviewPrompt',
  input: {schema: SelfReviewInputSchema},
  output: {schema: SelfReviewOutputSchema},
  config: {
    safetySettings: [
      { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
      { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
    ]
  },
  prompt: `You are a second-level AI assistant called Claude-Review. Your job is to review the output generated by another AI assistant named AIva.

Your task is to:
1. Evaluate the response for factual accuracy, clarity, tone, and safety.
2. Identify any logical inconsistencies or vague explanations.
3. Suggest improvements in the response.
4. If the answer is acceptable, affirm that it meets AIva's quality standards.

Respond in a structured JSON format according to the output schema.

User Prompt:
{{{userPrompt}}}

AIva Response:
{{{aiResponse}}}
`,
});

const selfReviewFlow = ai.defineFlow(
  {
    name: 'selfReviewFlow',
    inputSchema: SelfReviewInputSchema,
    outputSchema: SelfReviewOutputSchema,
  },
  async input => {
    const {output} = await selfReviewPrompt(input);
    if (!output) {
      throw new Error("Self-review flow failed to produce an output.");
    }
    return output;
  }
);


export async function selfReview(
  input: SelfReviewInput
): Promise<SelfReviewOutput> {
  return selfReviewFlow(input);
}
