'use server';
/**
 * @fileOverview An AI agent that reviews the output of another AI.
 *
 * - selfReview - A function that handles the self-review process.
 * - SelfReviewInput - The input type for the selfReview function.
 * - SelfReviewOutput - The return type for the selfReview function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SelfReviewInputSchema = z.object({
  userPrompt: z.string().describe("The user's original prompt to AIva."),
  aiResponse: z.string().describe('The response generated by AIva.'),
});
export type SelfReviewInput = z.infer<typeof SelfReviewInputSchema>;

const SelfReviewOutputSchema = z.object({
  summaryEvaluation: z
    .enum(['Good', 'Needs Improvement'])
    .describe('A brief evaluation of the response.'),
  issuesFound: z
    .string()
    .optional()
    .describe('Any logical inconsistencies, inaccuracies, or safety issues found.'),
  suggestedFixes: z
    .string()
    .optional()
    .describe('Specific suggestions for improving the response.'),
  finalVerdict: z
    .enum(['Use as-is', 'Revise'])
    .describe('The final decision on whether the response is ready to be used.'),
});
export type SelfReviewOutput = z.infer<typeof SelfReviewOutputSchema>;

export async function selfReview(
  input: SelfReviewInput
): Promise<SelfReviewOutput> {
  return selfReviewFlow(input);
}

const reviewPrompt = ai.definePrompt({
  name: 'selfReviewPrompt',
  input: { schema: SelfReviewInputSchema },
  output: { schema: SelfReviewOutputSchema },
  system: `You are a second-level AI assistant called Claude-Review. Your job is to review the output generated by another AI assistant named AIva, who is powered by Claude or Gemini.

Your task is to:
1. Evaluate the response for factual accuracy, clarity, tone, and safety.
2. Identify any logical inconsistencies or vague explanations.
3. Suggest improvements in the response.
4. If the answer is acceptable, affirm that it meets AIva's quality standards.

Respond in a structured way:
- ✔ Summary Evaluation (Good / Needs Improvement)
- 🧠 Issues Found (if any)
- 🛠 Suggested Fixes (if any)
- ✅ Final Verdict (Use as-is / Revise)

Always speak in a professional review tone, like a mentor helping another AI assistant.`,
  prompt: `Please review the following AIva response and give structured feedback.

User Prompt:
{{{userPrompt}}}

AIva Response:
{{{aiResponse}}}
`,
});

const selfReviewFlow = ai.defineFlow(
  {
    name: 'selfReviewFlow',
    inputSchema: SelfReviewInputSchema,
    outputSchema: SelfReviewOutputSchema,
  },
  async (input) => {
    const { output } = await reviewPrompt(input);
    return output!;
  }
);
